<#
.SYNOPSIS
    Regression tests for Module C validator checks (E4, E6, connector ID) added in Gate v3.

.DESCRIPTION
    Creates a minimal fixture solution under scripts\validator-fixtures\module-c-regression\,
    runs Test-AIGovernanceSource.ps1 against it, asserts the expected failures and warnings
    are present in the output, and cleans up.

    Four YAML fixtures are used:
      fixture-bad-columns   — triggers E6a (UserKey, ItemName), wrong connector, E4 (30m)
      fixture-llmdata       — triggers E6b (LLMEventData dynamic access)
      fixture-parser-ref    — triggers E6c (AIGS_CopilotActivity_Normalized reference)
      fixture-good          — MicrosoftCopilot connector, no forbidden columns,
                              PluginId only inside a watchlist let-block (stripping test)

    Exits 0 if all assertions pass, 1 if any assertion fails.

.NOTES
    Switch-owned. Do not edit without updating .squad/decisions/inbox/switch-module-c-validation-gates.md.
    See Gate v3 implementation record (2026-07-23T10:37:49-05:00).
#>

$ErrorActionPreference = 'Stop'
$script:Assertions = 0
$script:Failed     = 0

function Assert-Contains {
    param([string]$Text, [string]$Substring, [string]$Label)
    $script:Assertions++
    if ($Text.Contains($Substring)) {
        Write-Host "  PASS  $Label" -ForegroundColor Green
    } else {
        Write-Host "  FAIL  $Label" -ForegroundColor Red
        Write-Host "        Expected substring: $Substring" -ForegroundColor DarkRed
        $script:Failed++
    }
}

function Assert-NotContains {
    param([string]$Text, [string]$Substring, [string]$Label)
    $script:Assertions++
    if (-not $Text.Contains($Substring)) {
        Write-Host "  PASS  $Label" -ForegroundColor Green
    } else {
        Write-Host "  FAIL  $Label (unexpected match)" -ForegroundColor Red
        Write-Host "        Unwanted substring: $Substring" -ForegroundColor DarkRed
        $script:Failed++
    }
}

$thisDir   = $PSScriptRoot
$validator = Join-Path $thisDir "Test-AIGovernanceSource.ps1"
$fixRoot   = Join-Path $thisDir "validator-fixtures\module-c-regression"
$solRoot   = Join-Path $fixRoot "SolutionRoot"
$ruleDir   = Join-Path $solRoot "Analytic Rules"

# Clean up any residue from a previous interrupted run
if (Test-Path $fixRoot) { Remove-Item $fixRoot -Recurse -Force -ErrorAction SilentlyContinue }

try {
    # ── Create minimal fixture directory structure ───────────────────────────
    foreach ($d in @(
        $ruleDir,
        (Join-Path $solRoot "Watchlists"),
        (Join-Path $solRoot "Data")
    )) { $null = New-Item -ItemType Directory -Path $d -Force }

    # Stub docs (> 100 bytes to satisfy Check 8 size threshold)
    $stub = "# Regression fixture stub`r`nGenerated by Test-ModuleCChecks.ps1 for Module C validator regression tests.`r`nThis file satisfies the minimum size threshold for the documentation presence check.`r`n"
    foreach ($doc in @('PREREQUISITES.md', 'ReleaseNotes.md', 'CHANGELOG.md')) {
        Set-Content -Path (Join-Path $solRoot $doc) -Value $stub -NoNewline
    }

    # Minimal guids.json — no _roadmap section so Check 13 passes with "no _roadmap"
    Set-Content -Path (Join-Path $solRoot "guids.json") -Value '{ "_namespaceGuid": "f1de974b-f438-4719-b423-8bf704ba2aef" }' -NoNewline

    # ── Fixture 1: Bad columns + wrong connector + sub-hourly queryFrequency ─
    # Expected outcomes:
    #   E6a FAIL  — UserKey is a forbidden CopilotActivity column
    #   E6a FAIL  — ItemName is a forbidden CopilotActivity column
    #   Connector FAIL — connectorId 'WrongConnector' is not 'MicrosoftCopilot'
    #   E4 WARN   — queryFrequency '30m' (30 min) < 1h on a CopilotActivity rule
    Set-Content -Path (Join-Path $ruleDir "fixture-bad-columns.yaml") -Value @'
id: aabbccdd-1111-1111-1111-000000000001
name: "[FIXTURE] Bad columns and connector"
description: Test fixture for E6a forbidden columns, wrong connector ID, and E4 sub-hourly frequency.
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: WrongConnector
    dataTypes:
      - CopilotActivity
queryFrequency: 30m
queryPeriod: 1h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: N/A — CopilotActivity has no applicable ASIM schema
  // FIXTURE-001
  CopilotActivity
  | where UserKey == "test"
  | project TimeGenerated, UserKey, ItemName
'@ -NoNewline

    # ── Fixture 2: LLMEventData dynamic field access ─────────────────────────
    # Expected: E6b FAIL — LLMEventData dynamic column access
    Set-Content -Path (Join-Path $ruleDir "fixture-llmdata.yaml") -Value @'
id: aabbccdd-2222-2222-2222-000000000002
name: "[FIXTURE] LLMEventData dynamic access"
description: Test fixture for E6b LLMEventData dynamic field access check.
kind: Scheduled
severity: Medium
requiredDataConnectors: []
queryFrequency: 1h
queryPeriod: 1h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: N/A — CopilotActivity has no applicable ASIM schema
  // FIXTURE-002
  CopilotActivity
  | extend sessionId = LLMEventData.sessionId
  | project TimeGenerated, sessionId
'@ -NoNewline

    # ── Fixture 3: Custom parser reference ────────────────────────────────────
    # Expected: E6c FAIL — AIGS_CopilotActivity_Normalized referenced in KQL
    Set-Content -Path (Join-Path $ruleDir "fixture-parser-ref.yaml") -Value @'
id: aabbccdd-3333-3333-3333-000000000003
name: "[FIXTURE] Custom parser reference"
description: Test fixture for E6c custom parser reference check.
kind: Scheduled
severity: Medium
requiredDataConnectors: []
queryFrequency: 1h
queryPeriod: 1h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: N/A — CopilotActivity has no applicable ASIM schema
  // FIXTURE-003
  CopilotActivity
  | union (AIGS_CopilotActivity_Normalized | take 0)
  | where RecordType in ("CreateCopilotPlugin")
  | project TimeGenerated, RecordType
'@ -NoNewline

    # ── Fixture 4: Correct Module C rule ──────────────────────────────────────
    # Expected: connector PASS (MicrosoftCopilot), NO column FAIL, NO E4 WARN
    # Tests that PluginId inside a watchlist let-block is NOT flagged (stripping).
    Set-Content -Path (Join-Path $ruleDir "fixture-good.yaml") -Value @'
id: aabbccdd-4444-4444-4444-000000000004
name: "[FIXTURE] Correct Module C rule"
description: Test fixture for a valid Module C rule — correct connector, no forbidden columns.
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: MicrosoftCopilot
    dataTypes:
      - CopilotActivity
queryFrequency: 1h
queryPeriod: 4h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: N/A — CopilotActivity has no applicable ASIM schema
  // FIXTURE-004
  let ApprovedPlugins = materialize(
      _GetWatchlist("AIGS_ApprovedCopilotPlugins")
      | where Status =~ "Active"
      | project WL_PluginId = tolower(PluginId)
  );
  CopilotActivity
  | where TimeGenerated >= ago(4h)
  | where RecordType in ("CreateCopilotPlugin","UpdateCopilotPlugin","DeleteCopilotPlugin")
  | where Workload =~ "M365Copilot"
  | extend NormalizedPlugin = tolower(tostring(PluginName))
  | join kind=inner (ApprovedPlugins)
      on $left.NormalizedPlugin == $right.WL_PluginId
  | project TimeGenerated, RecordType, Workload, PluginName
'@ -NoNewline

    # ── Run the validator against the fixture solution root ──────────────────
    Write-Host ""
    Write-Host "============================================" -ForegroundColor Cyan
    Write-Host " Module C Validator Regression Tests (Gate v3)" -ForegroundColor Cyan
    Write-Host "============================================" -ForegroundColor Cyan
    Write-Host " Validator : $validator"
    Write-Host " Fixture   : $solRoot"
    Write-Host ""

    $outputRaw = & pwsh -NoProfile -NonInteractive -File $validator -SolutionRoot $solRoot 2>&1
    $output    = $outputRaw | Out-String

    Write-Host "── Assertions ──────────────────────────────" -ForegroundColor Cyan
    Write-Host ""

    # ── E6a: Forbidden column names ──────────────────────────────────────────
    Assert-Contains    $output "unverified CopilotActivity column 'UserKey'"    "E6a: UserKey forbidden column detected in fixture-bad-columns"
    Assert-Contains    $output "unverified CopilotActivity column 'ItemName'"   "E6a: ItemName forbidden column detected in fixture-bad-columns"

    # ── Connector: wrong ID rejected, correct ID accepted ────────────────────
    Assert-Contains    $output "connectorId 'WrongConnector'; required value is 'MicrosoftCopilot'"  "Connector FAIL: WrongConnector rejected"
    Assert-Contains    $output "connectorId 'MicrosoftCopilot' is correct"                           "Connector PASS: MicrosoftCopilot accepted in fixture-good"

    # ── E4: Sub-hourly queryFrequency warning ─────────────────────────────────
    Assert-Contains    $output "CopilotActivity rule has queryFrequency '30m'"  "E4 WARN: 30m queryFrequency on CopilotActivity triggers warning"

    # ── E6b: LLMEventData dynamic field ───────────────────────────────────────
    Assert-Contains    $output "unverified CopilotActivity dynamic column 'LLMEventData'"  "E6b: LLMEventData dynamic access detected"

    # ── E6c: Custom parser reference ─────────────────────────────────────────
    Assert-Contains    $output "references custom parser 'AIGS_CopilotActivity_Normalized'"  "E6c: Custom parser reference detected"

    # ── False-positive guards ─────────────────────────────────────────────────
    # Good fixture must not produce any MODULE-C column failure
    Assert-NotContains $output "fixture-good.yaml — unverified CopilotActivity column"  "No false-positive column FAIL on fixture-good"

    # PluginId inside watchlist let-block must NOT be flagged (stripping test)
    Assert-NotContains $output "fixture-good.yaml — unverified CopilotActivity column 'PluginId'"  "No false-positive PluginId from watchlist let-block (strip works)"

    # Good fixture must not trigger E4 warning (queryFrequency = 1h, not < 1h)
    Assert-NotContains $output "fixture-good.yaml — CopilotActivity rule has queryFrequency '1h'"  "No E4 WARN on fixture-good (1h >= threshold)"

} finally {
    # ── Clean up ──────────────────────────────────────────────────────────────
    if (Test-Path $fixRoot) { Remove-Item $fixRoot -Recurse -Force -ErrorAction SilentlyContinue }
}

Write-Host ""
Write-Host "── Results ─────────────────────────────────" -ForegroundColor Cyan
Write-Host " Assertions : $($script:Assertions)"
Write-Host " Passed     : $($script:Assertions - $script:Failed)" -ForegroundColor Green
Write-Host " Failed     : $($script:Failed)" -ForegroundColor $(if ($script:Failed -gt 0) { 'Red' } else { 'Green' })
Write-Host ""

if ($script:Failed -gt 0) {
    Write-Host "RESULT: FAILED — $($script:Failed) assertion(s) failed" -ForegroundColor Red
    exit 1
} else {
    Write-Host "RESULT: PASSED — all $($script:Assertions) assertions" -ForegroundColor Green
    exit 0
}
