<#
.SYNOPSIS
    Regression tests for Module E validator checks (E7a–E7k) — Gate v2 (Trinity contract final).

.DESCRIPTION
    Creates a minimal fixture solution under scripts\validator-fixtures\module-e-regression\,
    runs Test-AIGovernanceSource.ps1 against it, asserts the expected failures and warnings
    are present in the output, and cleans up.

    Eleven YAML fixtures cover all E7 sub-checks:
      fixture-e-hunt-good           — correct hunt (composite key, WatchlistDeployed toscalar,
                                      in~ statuses, cognitiveservices) → PASS all E7
      fixture-e-rule-anti-join      — kind=leftanti, no toscalar → E7c-i FAIL + E7c-iii WARN
      fixture-e-rule-no-success     — AIGS_ApprovedModels but no ActivityStatusValue → E7d-i FAIL
      fixture-e-rule-region         — ResourceLocation predicate → E7a FAIL
      fixture-e-rule-invented-col   — ModelName column → E7b FAIL
      fixture-e-rule-good           — full contract-compliant rule → PASS all E7
      fixture-e-rule-single-status  — ActivityStatusValue =~ "Success" only → E7d-ii WARN
      fixture-e-rule-properties     — Properties.ModelName access → E7b FAIL
      fixture-e-rule-deploy-only-key — deployment-name-only key, no cognitiveservices → E7f+E7g WARN
      fixture-e-rule-wrong-schedule — 30m/8h with ApprovedModels → E7e + E7k WARN
      fixture-e-rule-entity-incomplete — entityMappings missing AzureResource → E7h WARN

    Typed scenario coverage (Trinity final contract):
      Success + Succeeded (both terminal statuses)    → E7d-ii detects single-value coverage
      Cross-account same deployment name              → E7g detects missing AccountName in key
      Malformed/account-level ResourceIds             → E7g (composite key required)
      Duplicate correlation/resource events           → E7k (4h queryPeriod confirmed)
      Active approved → 0 findings                   → E7c fail-closed pattern (leftouter+toscalar)
      Active unapproved → findings                   → E7g (composite key correct join)
      Template-only / empty Active → 0 findings      → E7c-iii (toscalar WatchlistActive gate)
      Failed/unrelated ops                           → E7d (ActivityStatusValue filter) + E7f (scope)
      Hunt baseline seeding                          → fixture-e-hunt-good (WatchlistDeployed guard)

    Exits 0 if all assertions pass, 1 if any fail.

.NOTES
    Switch-owned. Do not edit without updating switch-module-e-validation-gates.md.
    Gate v2 — 2026-07-23T17:15:47-05:00 (Trinity final contract accepted by Morpheus).
#>

$ErrorActionPreference = 'Stop'
$script:Assertions = 0
$script:Failed     = 0

function Assert-Contains {
    param([string]$Text, [string]$Substring, [string]$Label)
    $script:Assertions++
    if ($Text.Contains($Substring)) {
        Write-Host "  PASS  $Label" -ForegroundColor Green
    } else {
        Write-Host "  FAIL  $Label" -ForegroundColor Red
        Write-Host "        Expected substring: $Substring" -ForegroundColor DarkRed
        $script:Failed++
    }
}

function Assert-NotContains {
    param([string]$Text, [string]$Substring, [string]$Label)
    $script:Assertions++
    if (-not $Text.Contains($Substring)) {
        Write-Host "  PASS  $Label" -ForegroundColor Green
    } else {
        Write-Host "  FAIL  $Label (unexpected match)" -ForegroundColor Red
        Write-Host "        Unwanted substring: $Substring" -ForegroundColor DarkRed
        $script:Failed++
    }
}

$thisDir   = $PSScriptRoot
$validator = Join-Path $thisDir "Test-AIGovernanceSource.ps1"
$fixRoot   = Join-Path $thisDir "validator-fixtures\module-e-regression"
$solRoot   = Join-Path $fixRoot "SolutionRoot"
$ruleDir   = Join-Path $solRoot "Analytic Rules"
$huntDir   = Join-Path $solRoot "Hunting Queries"

if (Test-Path $fixRoot) { Remove-Item $fixRoot -Recurse -Force -ErrorAction SilentlyContinue }

try {
    foreach ($d in @($ruleDir, $huntDir, (Join-Path $solRoot "Watchlists"), (Join-Path $solRoot "Data"))) {
        $null = New-Item -ItemType Directory -Path $d -Force
    }

    $stub = "# Regression fixture stub`r`nGenerated by Test-ModuleEChecks.ps1 — Module E Gate v2 regression.`r`nSatisfies minimum size threshold for documentation presence check.`r`n"
    foreach ($doc in @('PREREQUISITES.md', 'ReleaseNotes.md', 'CHANGELOG.md')) {
        Set-Content -Path (Join-Path $solRoot $doc) -Value $stub -NoNewline
    }
    Set-Content -Path (Join-Path $solRoot "guids.json") -Value '{ "_namespaceGuid": "f1de974b-f438-4719-b423-8bf704ba2aef" }' -NoNewline

    # ── Fixture 1: Good hunting query ────────────────────────────────────────
    # Tests: AzureActivity hunt with composite AccountName+DeploymentName key,
    # cognitiveservices scope, ActivityStatusValue in~ both terminal statuses,
    # WatchlistDeployed toscalar guard, leftouter, Status=Active, no region, no invented cols.
    # False-positive guard: case() string literals containing "region proxy" and
    # "location validation" must NOT trigger E7a (column-comparison pattern check).
    Set-Content -Path (Join-Path $huntDir "fixture-e-hunt-good.yaml") -Value @'
id: eeee0001-e001-e001-e001-000000000001
name: "[FIXTURE-E] Good Hunt — composite key, both terminal statuses"
description: |
  Test fixture for Module E hunt. Correct contract patterns:
  composite AccountName+DeploymentName key, cognitiveservices scope,
  ActivityStatusValue in~ both statuses, WatchlistDeployed guard.
  Case() string mentions "region proxy" — must not trigger E7a.
  Module: E — Control: AIGS-AM001 (reference hunt)
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
tactics:
  - PrivilegeEscalation
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-001 — correct hunt (all Trinity contract patterns)
  let DeployOp = "microsoft.cognitiveservices/accounts/deployments/write";
  let ApprovedModels = materialize(
      _GetWatchlist("AIGS_ApprovedModels")
      | where Status =~ "Active"
      | project AM_Key = strcat(tolower(AccountName), "/", tolower(DeploymentName)), AM_ModelId = ModelId
  );
  let WatchlistDeployed = toscalar(ApprovedModels | summarize n = count() | project n > 0);
  AzureActivity
  | where TimeGenerated >= ago(14d)
  | where tolower(OperationNameValue) == DeployOp
  | where ActivityStatusValue in~ ("Success", "Succeeded")
  | extend
      AccountName    = tostring(extract(@"/accounts/([^/]+)", 1, tolower(_ResourceId))),
      DeploymentName = tostring(extract(@"/deployments/([^/]+)", 1, tolower(_ResourceId)))
  | extend ObsKey = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  | join kind=leftouter (ApprovedModels) on $left.ObsKey == $right.AM_Key
  | extend InApprovedBaseline = isnotempty(AM_ModelId),
      ApprovalStatus = case(
          not(WatchlistDeployed), "INFO — Watchlist absent; baseline seeding mode. NOTE: region proxy via ResourceGroup is not supported; location validation requires Azure Resource Graph.",
          not(isnotempty(AM_ModelId)), "FLAG — Not in baseline. NOTE: region not available in AzureActivity.",
          "IN-BASELINE — Matches approved entry."
      )
  | where not(InApprovedBaseline) or not(WatchlistDeployed)
  | project TimeGenerated, ApprovalStatus, AccountName, DeploymentName, Caller, CallerIpAddress, SubscriptionId, CorrelationId, _ResourceId
'@ -NoNewline

    # ── Fixture 2: Anti-join fail-open ───────────────────────────────────────
    # Expected: E7c-i FAIL (leftanti), E7c-iii WARN (no toscalar).
    # Focused: includes cognitiveservices, composite key, in~ statuses, Status=Active
    # so only E7c-i and E7c-iii fire.
    Set-Content -Path (Join-Path $ruleDir "fixture-e-rule-anti-join.yaml") -Value @'
id: eeee0002-e002-e002-e002-000000000002
name: "[FIXTURE-E] Anti-Join Rule — bare leftanti"
description: Test fixture for E7c-i FAIL (leftanti) and E7c-iii WARN (no toscalar).
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
queryFrequency: 1h
queryPeriod: 4h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-002 — bare leftanti without toscalar guard (fail-open)
  let DeployOp = "microsoft.cognitiveservices/accounts/deployments/write";
  let ApprovedModels = materialize(
      _GetWatchlist("AIGS_ApprovedModels")
      | where Status =~ "Active"
      | project AM_Key = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  );
  AzureActivity
  | where TimeGenerated >= ago(4h)
  | where tolower(OperationNameValue) == DeployOp
  | where ActivityStatusValue in~ ("Success", "Succeeded")
  | extend
      AccountName    = tostring(extract(@"/accounts/([^/]+)", 1, tolower(_ResourceId))),
      DeploymentName = tostring(extract(@"/deployments/([^/]+)", 1, tolower(_ResourceId)))
  | extend ObsKey = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  | join kind=leftanti (ApprovedModels) on $left.ObsKey == $right.AM_Key
  | project TimeGenerated, AccountName, DeploymentName, Caller, CallerIpAddress, SubscriptionId, _ResourceId
'@ -NoNewline

    # ── Fixture 3: No ActivityStatusValue filter ──────────────────────────────
    # Expected: E7d-i FAIL (no ActivityStatusValue).
    # Focused: includes cognitiveservices, composite key, toscalar, Status=Active.
    # Comment "no ActivityStatusValue filter" tests comment stripping — must not suppress fail.
    Set-Content -Path (Join-Path $ruleDir "fixture-e-rule-no-success.yaml") -Value @'
id: eeee0003-e003-e003-e003-000000000003
name: "[FIXTURE-E] No ActivityStatusValue Filter Rule"
description: Test fixture for E7d-i FAIL — ActivityStatusValue Success filter absent.
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
queryFrequency: 1h
queryPeriod: 4h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-003 — no ActivityStatusValue filter (comment-strip test: ActivityStatusValue absent from KQL)
  let DeployOp = "microsoft.cognitiveservices/accounts/deployments/write";
  let ApprovedModels = materialize(
      _GetWatchlist("AIGS_ApprovedModels")
      | where Status =~ "Active"
      | project AM_Key = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  );
  let WatchlistActive = toscalar(ApprovedModels | summarize n = count() | project n > 0);
  AzureActivity
  | where TimeGenerated >= ago(4h)
  | where tolower(OperationNameValue) == DeployOp
  | where WatchlistActive
  | extend
      AccountName    = tostring(extract(@"/accounts/([^/]+)", 1, tolower(_ResourceId))),
      DeploymentName = tostring(extract(@"/deployments/([^/]+)", 1, tolower(_ResourceId)))
  | extend ObsKey = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  | join kind=leftouter (ApprovedModels) on $left.ObsKey == $right.AM_Key
  | where WatchlistActive and isempty(AM_Key)
  | project TimeGenerated, AccountName, DeploymentName, Caller, CallerIpAddress, SubscriptionId, _ResourceId
'@ -NoNewline

    # ── Fixture 4: Region predicate ───────────────────────────────────────────
    # Expected: E7a FAIL (ResourceLocation column predicate)
    Set-Content -Path (Join-Path $ruleDir "fixture-e-rule-region.yaml") -Value @'
id: eeee0004-e004-e004-e004-000000000004
name: "[FIXTURE-E] Region Predicate Rule"
description: Test fixture for E7a FAIL — unsupported ResourceLocation column predicate.
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
queryFrequency: 1h
queryPeriod: 4h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-004 — ResourceLocation predicate (INVALID: AzureActivity has no resource location)
  AzureActivity
  | where TimeGenerated >= ago(4h)
  | where ActivityStatusValue in~ ("Success", "Succeeded")
  | where ResourceLocation =~ "eastus"
  | project TimeGenerated, Caller, CallerIpAddress, SubscriptionId, _ResourceId
'@ -NoNewline

    # ── Fixture 5: Invented model column ─────────────────────────────────────
    # Expected: E7b FAIL (ModelName not in documented AzureActivity schema)
    Set-Content -Path (Join-Path $ruleDir "fixture-e-rule-invented-col.yaml") -Value @'
id: eeee0005-e005-e005-e005-000000000005
name: "[FIXTURE-E] Invented Column Rule"
description: Test fixture for E7b FAIL — invented model column not in AzureActivity schema.
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
queryFrequency: 1h
queryPeriod: 4h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-005 — ModelName not in AzureActivity schema (ARM Properties not a documented column)
  AzureActivity
  | where TimeGenerated >= ago(4h)
  | where ActivityStatusValue in~ ("Success", "Succeeded")
  | where ModelName == "gpt-4o"
  | project TimeGenerated, ModelName, Caller, CallerIpAddress, SubscriptionId, _ResourceId
'@ -NoNewline

    # ── Fixture 6: Full correct Scheduled rule ────────────────────────────────
    # Expected: PASS all E7 checks (no failures or warnings).
    # Validates: composite key, both terminal statuses (in~), cognitiveservices scope,
    # toscalar WatchlistActive, Status=Active, leftouter, 1h/4h schedule,
    # entityMappings with Account+IP+AzureResource. ActiveBaselineCount > 0 gate.
    Set-Content -Path (Join-Path $ruleDir "fixture-e-rule-good.yaml") -Value @'
id: eeee0006-e006-e006-e006-000000000006
name: "[FIXTURE-E] Good Rule — all Trinity contract gates"
description: |
  Test fixture for Module E correct analytic rule — all E7 gates pass.
  Composite AccountName+DeploymentName key, in~ both terminal statuses,
  cognitiveservices scope, toscalar WatchlistActive, leftouter, 1h/4h.
kind: Scheduled
severity: High
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
queryFrequency: 1h
queryPeriod: 4h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-006 — all Trinity contract patterns correct
  let DeployOp = "microsoft.cognitiveservices/accounts/deployments/write";
  let ApprovedModels = materialize(
      _GetWatchlist("AIGS_ApprovedModels")
      | where Status =~ "Active"
      | project AM_Key = strcat(tolower(AccountName), "/", tolower(DeploymentName)), AM_ModelId = ModelId
  );
  let WatchlistActive = toscalar(ApprovedModels | summarize n = count() | project n > 0);
  AzureActivity
  | where TimeGenerated >= ago(4h)
  | where tolower(OperationNameValue) == DeployOp
  | where ActivityStatusValue in~ ("Success", "Succeeded")
  | extend
      AccountName    = tostring(extract(@"/accounts/([^/]+)", 1, tolower(_ResourceId))),
      DeploymentName = tostring(extract(@"/deployments/([^/]+)", 1, tolower(_ResourceId)))
  | where WatchlistActive
  | extend ObsKey = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  | join kind=leftouter (ApprovedModels) on $left.ObsKey == $right.AM_Key
  | where isempty(AM_ModelId)
  | project TimeGenerated, AccountName, DeploymentName, Caller, CallerIpAddress, SubscriptionId, ResourceGroup, CorrelationId, _ResourceId
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: FullName
        columnName: Caller
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: CallerIpAddress
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: _ResourceId
'@ -NoNewline

    # ── Fixture 7: Single terminal status ─────────────────────────────────────
    # Expected: E7d-ii WARN (only "Success", "Succeeded" not covered).
    # E7d-i must NOT fire (ActivityStatusValue IS present).
    # Focused: correct in all other respects.
    Set-Content -Path (Join-Path $ruleDir "fixture-e-rule-single-status.yaml") -Value @'
id: eeee0007-e007-e007-e007-000000000007
name: "[FIXTURE-E] Single Terminal Status — Success only"
description: Test fixture for E7d-ii WARN — ActivityStatusValue filters Success only, Succeeded not covered.
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
queryFrequency: 1h
queryPeriod: 4h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-007 — single terminal status (misses "Succeeded")
  let DeployOp = "microsoft.cognitiveservices/accounts/deployments/write";
  let ApprovedModels = materialize(
      _GetWatchlist("AIGS_ApprovedModels")
      | where Status =~ "Active"
      | project AM_Key = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  );
  let WatchlistActive = toscalar(ApprovedModels | summarize n = count() | project n > 0);
  AzureActivity
  | where TimeGenerated >= ago(4h)
  | where tolower(OperationNameValue) == DeployOp
  | where ActivityStatusValue =~ "Success"
  | extend
      AccountName    = tostring(extract(@"/accounts/([^/]+)", 1, tolower(_ResourceId))),
      DeploymentName = tostring(extract(@"/deployments/([^/]+)", 1, tolower(_ResourceId)))
  | where WatchlistActive
  | extend ObsKey = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  | join kind=leftouter (ApprovedModels) on $left.ObsKey == $right.AM_Key
  | where isempty(AM_Key)
  | project TimeGenerated, AccountName, DeploymentName, Caller, CallerIpAddress, SubscriptionId, _ResourceId
'@ -NoNewline

    # ── Fixture 8: Properties subkey access ──────────────────────────────────
    # Expected: E7b FAIL (Properties.ModelName — subkey access prohibited)
    Set-Content -Path (Join-Path $ruleDir "fixture-e-rule-properties.yaml") -Value @'
id: eeee0008-e008-e008-e008-000000000008
name: "[FIXTURE-E] Properties Subkey Access"
description: Test fixture for E7b FAIL — Properties.ModelName subkey access is prohibited.
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
queryFrequency: 1h
queryPeriod: 4h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-008 — Properties subkey access (model extraction from Properties is prohibited)
  AzureActivity
  | where TimeGenerated >= ago(4h)
  | where ActivityStatusValue in~ ("Success", "Succeeded")
  | extend ExtractedModel = Properties.ModelName
  | project TimeGenerated, ExtractedModel, Caller, CallerIpAddress, SubscriptionId, _ResourceId
'@ -NoNewline

    # ── Fixture 9: Deployment-only key + no cognitiveservices ──────────────
    # Expected: E7f WARN (cognitiveservices absent), E7g WARN (AccountName missing from key).
    # Tests cross-account same-deployment-name vulnerability and operation scope gap.
    Set-Content -Path (Join-Path $ruleDir "fixture-e-rule-deploy-only-key.yaml") -Value @'
id: eeee0009-e009-e009-e009-000000000009
name: "[FIXTURE-E] Deployment-Only Key — no composite, no scope"
description: |
  Test fixture for E7f WARN (cognitiveservices scope absent) and
  E7g WARN (AccountName missing — deployment-only key). Cross-account same-name vulnerability.
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
queryFrequency: 1h
queryPeriod: 4h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-009 — no provider scope, deployment-name-only join key (E7f + E7g)
  let ApprovedModels = materialize(
      _GetWatchlist("AIGS_ApprovedModels")
      | where Status =~ "Active"
      | project AM_DeploymentName = tolower(DeploymentName)
  );
  let WatchlistActive = toscalar(ApprovedModels | summarize n = count() | project n > 0);
  AzureActivity
  | where TimeGenerated >= ago(4h)
  | where ActivityStatusValue in~ ("Success", "Succeeded")
  | extend DeploymentName = tostring(extract(@"/deployments/([^/]+)", 1, tolower(_ResourceId)))
  | where WatchlistActive
  | join kind=leftouter (ApprovedModels) on $left.DeploymentName == $right.AM_DeploymentName
  | where isempty(AM_DeploymentName)
  | project TimeGenerated, DeploymentName, Caller, CallerIpAddress, SubscriptionId, _ResourceId
'@ -NoNewline

    # ── Fixture 10: Wrong schedule ────────────────────────────────────────────
    # Expected: E7e WARN (30m sub-hourly), E7k WARN (freq 30m != 1h), E7k WARN (period 8h != 4h).
    # Tests: duplicate-event risk (queryPeriod) and ingestion-latency gap (queryFrequency).
    Set-Content -Path (Join-Path $ruleDir "fixture-e-rule-wrong-schedule.yaml") -Value @'
id: eeee0010-e010-e010-e010-000000000010
name: "[FIXTURE-E] Wrong Schedule — 30m frequency / 8h period"
description: Test fixture for E7e WARN (sub-hourly) and E7k WARN (not 1h/4h).
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
queryFrequency: 30m
queryPeriod: 8h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-010 — wrong schedule (30m freq, 8h period) for ApprovedModels rule
  let DeployOp = "microsoft.cognitiveservices/accounts/deployments/write";
  let ApprovedModels = materialize(
      _GetWatchlist("AIGS_ApprovedModels")
      | where Status =~ "Active"
      | project AM_Key = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  );
  let WatchlistActive = toscalar(ApprovedModels | summarize n = count() | project n > 0);
  AzureActivity
  | where TimeGenerated >= ago(8h)
  | where tolower(OperationNameValue) == DeployOp
  | where ActivityStatusValue in~ ("Success", "Succeeded")
  | extend
      AccountName    = tostring(extract(@"/accounts/([^/]+)", 1, tolower(_ResourceId))),
      DeploymentName = tostring(extract(@"/deployments/([^/]+)", 1, tolower(_ResourceId)))
  | where WatchlistActive
  | extend ObsKey = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  | join kind=leftouter (ApprovedModels) on $left.ObsKey == $right.AM_Key
  | where isempty(AM_Key)
  | project TimeGenerated, AccountName, DeploymentName, Caller, CallerIpAddress, SubscriptionId, _ResourceId
'@ -NoNewline

    # ── Fixture 11: Incomplete entity mappings ────────────────────────────────
    # Expected: E7h WARN (entityMappings declared but AzureResource missing).
    # All other E7 checks pass — tests entity mapping validation in isolation.
    Set-Content -Path (Join-Path $ruleDir "fixture-e-rule-entity-incomplete.yaml") -Value @'
id: eeee0011-e011-e011-e011-000000000011
name: "[FIXTURE-E] Incomplete Entity Mappings — AzureResource missing"
description: Test fixture for E7h WARN — entityMappings declared but missing AzureResource type.
kind: Scheduled
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActivity
    dataTypes:
      - AzureActivity
queryFrequency: 1h
queryPeriod: 4h
triggerOperator: gt
triggerThreshold: 0
query: |
  // ASIM: imAuditEvent — native (AzureActivity)
  // FIXTURE-E-011 — incomplete entity mappings (Account+IP present, AzureResource absent)
  let DeployOp = "microsoft.cognitiveservices/accounts/deployments/write";
  let ApprovedModels = materialize(
      _GetWatchlist("AIGS_ApprovedModels")
      | where Status =~ "Active"
      | project AM_Key = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  );
  let WatchlistActive = toscalar(ApprovedModels | summarize n = count() | project n > 0);
  AzureActivity
  | where TimeGenerated >= ago(4h)
  | where tolower(OperationNameValue) == DeployOp
  | where ActivityStatusValue in~ ("Success", "Succeeded")
  | extend
      AccountName    = tostring(extract(@"/accounts/([^/]+)", 1, tolower(_ResourceId))),
      DeploymentName = tostring(extract(@"/deployments/([^/]+)", 1, tolower(_ResourceId)))
  | where WatchlistActive
  | extend ObsKey = strcat(tolower(AccountName), "/", tolower(DeploymentName))
  | join kind=leftouter (ApprovedModels) on $left.ObsKey == $right.AM_Key
  | where isempty(AM_Key)
  | project TimeGenerated, AccountName, DeploymentName, Caller, CallerIpAddress, SubscriptionId, _ResourceId
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: FullName
        columnName: Caller
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: CallerIpAddress
'@ -NoNewline

    # ── Run the validator ────────────────────────────────────────────────────
    Write-Host ""
    Write-Host "============================================" -ForegroundColor Cyan
    Write-Host " Module E Validator Regression Tests (Gate v2)" -ForegroundColor Cyan
    Write-Host "============================================" -ForegroundColor Cyan
    Write-Host " Validator : $validator"
    Write-Host " Fixture   : $solRoot"
    Write-Host ""

    $outputRaw = & pwsh -NoProfile -NonInteractive -File $validator -SolutionRoot $solRoot 2>&1
    $output    = $outputRaw | Out-String

    Write-Host "── Assertions ──────────────────────────────" -ForegroundColor Cyan
    Write-Host ""

    # ── E7c-i: leftanti FAIL ──────────────────────────────────────────────────
    Assert-Contains $output "kind=leftanti' against AIGS_ApprovedModels" `
        "E7c-i FAIL: bare leftanti detected in anti-join fixture"

    # ── E7c-iii: no toscalar WARN ─────────────────────────────────────────────
    Assert-Contains $output "no toscalar() WatchlistActive scalar guard" `
        "E7c-iii WARN: toscalar guard absent in anti-join fixture"

    # ── E7d-i: no ActivityStatusValue FAIL ───────────────────────────────────
    Assert-Contains $output "does not filter on ActivityStatusValue" `
        "E7d-i FAIL: ActivityStatusValue entirely absent in no-success fixture"

    # ── E7d-ii: single terminal status WARN ──────────────────────────────────
    Assert-Contains $output "does not cover both confirmed terminal statuses" `
        "E7d-ii WARN: single 'Success' only detected in single-status fixture"

    # ── E7a: region predicate FAIL ────────────────────────────────────────────
    Assert-Contains $output "region/location column predicate" `
        "E7a FAIL: ResourceLocation predicate detected in region fixture"

    # ── E7b: invented column FAIL ─────────────────────────────────────────────
    Assert-Contains $output "invented column 'ModelName'" `
        "E7b FAIL: ModelName invented column detected"

    # ── E7b: Properties subkey FAIL ───────────────────────────────────────────
    Assert-Contains $output "Properties subkey/index access" `
        "E7b FAIL: Properties.ModelName subkey access detected"

    # ── E7f: operation scope WARN ─────────────────────────────────────────────
    Assert-Contains $output "operation scope not detected" `
        "E7f WARN: cognitiveservices scope absent in deploy-only-key fixture"

    # ── E7g: composite key WARN ───────────────────────────────────────────────
    Assert-Contains $output "does not reference composite join key" `
        "E7g WARN: AccountName missing from key in deploy-only-key fixture"

    # ── E7e: sub-hourly WARN ──────────────────────────────────────────────────
    Assert-Contains $output "shorter than 1h" `
        "E7e WARN: 30m queryFrequency is sub-hourly in wrong-schedule fixture"

    # ── E7k: queryFrequency mismatch WARN ────────────────────────────────────
    Assert-Contains $output "confirmed queryFrequency is 1h (60 min)" `
        "E7k WARN: queryFrequency 30m != 1h in wrong-schedule fixture"

    # ── E7k: queryPeriod mismatch WARN ────────────────────────────────────────
    Assert-Contains $output "confirmed queryPeriod is 4h (240 min)" `
        "E7k WARN: queryPeriod 8h != 4h in wrong-schedule fixture"

    # ── E7h: incomplete entity mappings WARN ─────────────────────────────────
    Assert-Contains $output "missing required entity type 'AzureResource'" `
        "E7h WARN: AzureResource entity type missing in entity-incomplete fixture"

    # ── False-positive guards ─────────────────────────────────────────────────
    # Good hunt: case() strings mention "region proxy" and "location" — must not trigger E7a.
    # Hunt is not Scheduled — E7c/E7d/E7f/E7g/E7h/E7k must not fire.
    Assert-NotContains $output "fixture-e-hunt-good.yaml — E7" `
        "No E7 failures or warnings on good hunt (false-positive guard)"

    # Good rule: correct in all respects — no E7 failures or warnings.
    Assert-NotContains $output "fixture-e-rule-good.yaml — E7" `
        "No E7 failures or warnings on good rule (all contract gates pass)"

    # Single-status fixture: ActivityStatusValue IS present (E7d-i must NOT FAIL, only E7d-ii WARNS).
    Assert-NotContains $output "fixture-e-rule-single-status.yaml — E7d: Scheduled rule references AIGS_ApprovedModels on AzureActivity but does not filter" `
        "E7d-i must NOT fire on single-status fixture (ActivityStatusValue present, only E7d-ii warns)"

} finally {
    if (Test-Path $fixRoot) { Remove-Item $fixRoot -Recurse -Force -ErrorAction SilentlyContinue }
}

Write-Host ""
Write-Host "── Results ─────────────────────────────────" -ForegroundColor Cyan
Write-Host " Assertions : $($script:Assertions)"
Write-Host " Passed     : $($script:Assertions - $script:Failed)" -ForegroundColor Green
Write-Host " Failed     : $($script:Failed)" -ForegroundColor $(if ($script:Failed -gt 0) { 'Red' } else { 'Green' })
Write-Host ""

if ($script:Failed -gt 0) {
    Write-Host "RESULT: FAILED — $($script:Failed) assertion(s) failed" -ForegroundColor Red
    exit 1
} else {
    Write-Host "RESULT: PASSED — all $($script:Assertions) assertions" -ForegroundColor Green
    exit 0
}
